language: php
php:
  - '7.0'
sudo: required
before_script:
  - php5dismod xdebug
  - composer install
  - php5enmod xdebug
script:
  - phpunit
cache:
  directories:
  - vendor
  files:
  - composer.lock