language: php
php:
  - '7.0'
sudo: required
before_script:
  - phpenv config-rm xdebug.ini
  - composer install
  - phpenv config-add xdebug.ini
script:
  - phpunit
cache:
  directories:
  - vendor
  files:
  - composer.lock