language: php
php:
  - '7.0'
sudo: required
before_script:
  - phpdismod xdebug
  - composer install
  - phpenmod xdebug
script:
  - phpunit
cache:
  directories:
  - vendor
  files:
  - composer.lock