language: php
php:
  - '7.0'
sudo: required
before_script:
  - composer install
script:
  - phpunit
cache:
  directories:
  - vendor
  files:
  - composer.lock
after_success:
  - bash <(curl -s https://codecov.io/bash)